[package]
org = "ballerina"
name = "websubhub"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "cache"
version = "@stdlib.cache.version@"

[[dependency]]
org = "ballerina"
name = "auth"
version = "@stdlib.auth.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "encoding"
version = "@stdlib.encoding.version@"

[[dependency]]
org = "ballerina"
name = "mime"
version = "@stdlib.mime.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[dependency]]
org = "ballerina"
name = "config"
version = "@stdlib.configapi.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "http"
version = "@stdlib.http.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "@stdlib.uuid.version@"

[[platform.java11.dependency]]
path = "../websubhub-native/build/libs/websubhub-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "web-sub"
version = "@project.version@"


[[platform.java11.dependency]]
path = "./lib/http-native-@http.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "http-native"
version = "@http.native.version@"


[[platform.java11.dependency]]
path = "./lib/netty-common-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-buffer-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-transport-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-transport"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-resolver-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-resolver"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-handler-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-handler"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-codec-http-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-codec-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "@netty.version@"


[[platform.java11.dependency]]
path = "./lib/commons-pool-@wso2commonspool.version@.jar"
groupId = "commons-pool.wso2"
artifactId = "commons-pool"
version = "@wso2commonspool.version@"


[[platform.java11.dependency]]
path = "./lib/snakeyaml-@wso2snakeyaml.version@.jar"
groupId = "org.wso2.orbit.org.yaml"
artifactId = "snakeyaml"
version = "@wso2snakeyaml.version@"


[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "@bouncycastle.version@"


[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-@bouncycastle.version@.jar"
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "@bouncycastle.version@"


[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@nettytcnative.version@.jar"
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "@nettytcnative.version@"


[[platform.java11.dependency]]
path = "./lib/broker-core-@ballerinambcore.version@.jar"
groupId = "io.ballerina.messaging"
artifactId = "broker-core"
version = "@ballerinambcore.version@"


[[platform.java11.dependency]]
path = "./lib/broker-common-@ballerinamb.version@.jar"
groupId = "io.ballerina.messaging"
artifactId = "broker-common"
version = "@ballerinamb.version@"


[[platform.java11.dependency]]
path = "./lib/broker-auth-@ballerinamb.version@.jar"
groupId = "io.ballerina.messaging"
artifactId = "broker-auth"
version = "@ballerinamb.version@"


[[platform.java11.dependency]]
path = "./lib/broker-rest-runner-@ballerinamb.version@.jar"
groupId = "io.ballerina.messaging"
artifactId = "broker-rest-runner"
version = "@ballerinamb.version@"


[[platform.java11.dependency]]
path = "./lib/broker-coordination-@ballerinamb.version@.jar"
groupId = "io.ballerina.messaging"
artifactId = "broker-coordination"
version = "@ballerinamb.version@"


[[platform.java11.dependency]]
path = "./lib/org.wso2.carbon.metrics.core-@wso2carbonmetrics.version@.jar"
groupId = "org.wso2.carbon.metrics"
artifactId = "org.wso2.carbon.metrics.core"
version = "@wso2carbonmetrics.version@"


[[platform.java11.dependency]]
path = "./lib/guava-@guava.version@.jar"
groupId = "com.google.guava"
artifactId = "guava"
version = "@guava.version@"
