[package]
org = "wso2"
name = "jmshub"
version = "0.1.0"
distribution = "2201.10.5"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId="com.ibm.mq"
artifactId="com.ibm.mq.allclient"
version="9.4.0.10"

[[platform.java17.dependency]]
path="/<path-to>/fscontext.jar"

[[platform.java17.dependency]]
path="/<path-to>/providerutil.jar"
